#!/usr/bin/env /SNS/users/j35/miniconda3/envs/my_imars3d-dev/bin/python

import os
import sys
import getopt


def main(argv):

    opts, args = getopt.getopt(argv, "hi:o", ["ipts'"])    

    for opt, arg in opts:

        if opts == '-h':
            print("start_cg1d_ipts_notebooks <ipts_number>")
            sys.exit()

        elif opt in ("-i", "--ipts"):
            ipts = arg

    os.chdir(f"/HFIR/CG1D/IPTS-{ipts}/shared/notebooks/")
    os.system("/SNS/users/j35/miniconda3/envs/my_imars3d-dev/bin/jupyter notebook")

if __name__ == "__main__":
    main(sys.argv[1:])
